### PR TITLE
added name of the website in the navbar,and worked on responsivness.

### PR DESCRIPTION
**Pull request by pankajsingh92533**
https://github.com/lazyjinchuriki/cinephile/assets/125594928/54b6a057-8b2c-4e26-a327-2aca889e630e

please verify it.

### CODE REVIEW

**Comment by lazyjinchuriki** [comment]
Is is mobile responsive?

**Comment by pankajsingh92533** [comment]
yes,it is mobile responsive .

https://github.com/lazyjinchuriki/cinephile/assets/125594928/e456e0c9-15f3-459f-95e5-d8db8676d78f

**Comment by lazyjinchuriki** [comment]
Can you make is so that in mobile  view the term "cinephile" goes to the top.

**Comment by pankajsingh92533** [comment]
https://github.com/lazyjinchuriki/cinephile/assets/125594928/00a3e103-2f10-42c2-82c1-cfff4fd27631

i have made changes as per instructions.Please review it.

**Comment by lazyjinchuriki** [comment]
It's still not correct.
Nevertheless I'm merging it.

**Pull request merged**
