### PR TITLE
Changes added to Navbar 

### PR DESCRIPTION
**Pull request by rishirajm007**
1. added a home icon in the nav bar.
2. added search icon

### CODE REVIEW

**Comment by lazyjinchuriki** [comment]
Kindly show the images for mobile view as i can not review your code now.

**Comment by rishirajm007** [comment]
mobile view screenshot

image

**Comment by lazyjinchuriki** [comment]
It's not responsive is it.

**Comment by rishirajm007** [comment]
It is responsive.

**Comment by rishirajm007** [comment]
Here is proof of responsive. Hope you like it. 

https://github.com/lazyjinchuriki/cinephile/assets/120004473/cc852e34-4074-478c-84d9-1a2a02503cbb

**Comment by lazyjinchuriki** [comment]
That doesn't count as responsive.

**Pull request closed without merging**
