### PR TITLE
Added a logo

### PR DESCRIPTION
**Pull request by GD0910**
added logo 
Solves issue  #16 

Screenshots 
image

### CODE REVIEW

**Comment by GD0910** [comment]
@lazyjinchuriki can u check this PR

**Comment by GD0910** [comment]
@lazyjinchuriki can you explain this issue I am new to open source and i tried changing the code as well 

image

**Comment by lazyjinchuriki** [comment]
Github shows this when there are some conflicts with merging the pr, it's nothing you should worry about, but about the pr it is not mobile responsive.
Sorry i can't merge it.

**Comment by GD0910** [comment]
> Github shows this when there are some conflicts with merging the pr, it's nothing you should worry about, but about the pr it is not mobile responsive. Sorry i can't merge it.

ok will try again but how to check if it is mobile responsive or not Any tips

**Comment by lazyjinchuriki** [comment]
Go to inspect there you can check your website how it looks in different devices

**Comment by GD0910** [comment]
> Go to inspect there you can check your website how it looks in different devices

Thank you will work on this issue 
can you assign this issue under hacktoberfest tag

**Pull request closed without merging**
